version: "3"
services:
  app:
    container_name: node-api
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
